# Generated by Django 3.0.5 on 2022-04-25 04:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('exam_creation_date', models.DateTimeField(default=datetime.datetime(2022, 4, 25, 7, 52, 9, 652142))),
                ('is_published', models.BooleanField(default=False)),
                ('num_of_questions', models.IntegerField(default=0)),
                ('exam_type', models.SlugField(blank=True, null=True)),
                ('exam_time', models.IntegerField(default=0)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='users.MyUser')),
                ('students', models.ManyToManyField(related_name='_exam_students_+', to='users.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='TakenExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('full_mark', models.IntegerField()),
                ('done_date', models.DateTimeField(default=datetime.datetime(2022, 4, 25, 7, 52, 9, 661142))),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=4096)),
                ('op1', models.CharField(max_length=255)),
                ('op2', models.CharField(max_length=255)),
                ('op3', models.CharField(max_length=255)),
                ('op4', models.CharField(max_length=255)),
                ('correct_ans', models.IntegerField()),
                ('hint', models.CharField(max_length=255, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Exam')),
            ],
        ),
    ]
