# Generated by Django 3.0.5 on 2022-05-16 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 0, 13, 57, 7837)),
        ),
        migrations.AlterField(
            model_name='takenexam',
            name='done_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 0, 13, 57, 17838)),
        ),
    ]
