# Generated by Django 3.0.5 on 2022-05-16 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220517_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 2, 40, 20, 540705)),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='takenexam',
            name='done_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 2, 40, 20, 550705)),
        ),
    ]
